In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
filepath='/Users/macbookpro/Desktop/User_Data.csv'

In [3]:
dataset = pd.read_csv(filepath)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/macbookpro/Desktop/User_Data.csv'

In [4]:
dataset.shape


NameError: name 'dataset' is not defined

In [5]:
dataset.head(20)

NameError: name 'dataset' is not defined

User Database – This dataset contains information of users from a companies database. It contains information about UserID, Gender, Age, EstimatedSalary, Purchased. We are using this dataset for predicting that a user will purchase the company’s newly launched product or not.

# Let’s make the Logistic Regression model...
predicting whether a user will purchase the product or not.

In [44]:
#Now, to predict whether a user will purchase the product or not,
#one needs to find out the relationship between Age and Estimated Salary.
#Here User ID and Gender are not important factors for finding out this.

x = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values



In [45]:
#Splitting the dataset to train and test.
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [46]:
#Now, it is very important to perform feature scaling here
#because Age and Estimated Salary values lie in different ranges.
#If we don’t scale the features
#then Estimated Salary feature will dominate Age feature
#Here once see that Age and Estimated salary features values are sacled and now there in the -1 to 1.
#Hence, each feature will contribute equally in decision making i.e. finalizing the hypothesis.

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print (xtrain)

print (xtest)

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]]


In [47]:
print (xtest[0:10, :])



[[-0.80480212  0.50496393]
 [-0.01254409 -0.5677824 ]
 [-0.30964085  0.1570462 ]
 [-0.80480212  0.27301877]
 [-0.30964085 -0.5677824 ]
 [-1.10189888 -1.43757673]
 [-0.70576986 -1.58254245]
 [-0.21060859  2.15757314]
 [-1.99318916 -0.04590581]
 [ 0.8787462  -0.77073441]]


In [48]:
#Finally, we are training our Logistic Regression model.
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)


/Users/macbookpro/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
#After training the model, it time to use it to do prediction on testing data.
y_pred = classifier.predict(xtest)

In [50]:
#Let’s test the performance of our model – Confusion Matrix 62.
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)
print ("Confusion Matrix : \n", cm)

#Performance measure – Accuracy
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(ytest, y_pred))


Confusion Matrix : 
 [[65  3]
 [ 8 24]]
Accuracy :  0.89


 TruePostive + TrueNegative = 65 + 24
 
 FalsePositive + FalseNegative = 3 + 8